### Get tasks
GET http://localhost:3001/

### Add new task
POST http://localhost:3001/new
Content-Type: application/json

{
    "description": "Test from  client"
}


### Delete a task
DELETE http://localhost:3001/delete/1 HTTP/1.1